### ISSUE TITLE
Create components package

### ISSUE THREAD

**Issue by ZHollingshead** [aurelia/ux#104]
The components package is to install all components at once for those that want everything included with UX.

```json
dependencies: {
  "@aurelia-ux/core": "0.4.0",
  "@aurelia-ux/components": "0.4.0"
}
```

Instead of

```json
dependencies: {
  "@aurelia-ux/core": "0.4.0",
  "@aurelia-ux/button": "0.4.0",
  "@aurelia-ux/input": "0.4.0",
  "@aurelia-ux/input-info": "0.4.0",
  "@aurelia-ux/checkbox": "0.4.0",
  ...
}
```

**Comment by ZHollingshead** [comment]
Alternatively, if I could get the setup working, we could also have an `@aurelia-ux/all` package instead which contains the core and all components, which I think would be ideal. I do not think there is anything in the core that would prevent this.

@EisenbergEffect what are your thoughts?

**Comment by EisenbergEffect** [comment]
I like that idea.
