### ISSUE TITLE
ux-button : Incorrect reference to paper-ripple.css

### ISSUE THREAD

**Issue by ben-girardet** [aurelia/ux#108]
**I'm submitting a bug report**

* **Library Version:**
0.4.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

Aurelia-cli with require.js

* **Browser:**
all 

* **Language:**
TypeScript X.X

**Current behavior:**
The button components doesn't load properly due to false reference to the paper-ripple.css file from the ux-button.html

**Expected/desired behavior:**

Correct loading of the paper-ripple.css file

**Fix ?**

Edit the https://github.com/aurelia/ux/blob/master/packages/button/src/ux-button.html file (line 2) and reference the paper-ripple.css file with `@aurelia-ux/core`:

```html
<require from="@aurelia-ux/core/effects/paper-ripple.css"></require>
```

**Comment by ZHollingshead** [comment]
Thanks for the submission and potential fix. I did a quick check and this bug also applies to the checkbox.
