### ISSUE TITLE
New ux component boilerplate

### ISSUE THREAD

**Issue by foureggs** [aurelia/ux#11]
If you want the community to make custom ux components used in production, you should make some kind of a boilerplate for a custom component that we can just download and build a new component with, so components made by different people follow the same code structure. 

This would make it more readable for the aurelia ux team, allow us to make components faster and let you implement them quicker without changing the code structure as it already follows your boilerplate conventions.

I encountered this problem today when I was writing a material design ux-slider, but I just had no idea how to implement it as the ux-button is, so please give us some feedback; a boilerplate or a guide would do.

**Comment by shannonhorn** [comment]
great idea and it's in the works. we'll introduce UX component guidelines / best practices and a boilerplate to use to get started.

**Comment by inhuman-programmer** [comment]
I guess I will wait until you guys release it, let us know somewhere when it's done, maybe blog.aurelia.io would be a good place.

**Comment by EisenbergEffect** [comment]
Sounds like a plan :)

**Comment by Ganbin** [comment]
Aurelia-CLI generator could make the deal? But of course some guidelines will be helpful.

**Comment by xiwc** [comment]
I have found lots of UX impl base on Angular rect vue, but aurelia. It's cool if there is one based on aurelia.

Now our project use semantic-ui & aurelia. It's not comfortable because of i have do lots of init work for UI.

**Comment by ZHollingshead** [comment]
Issue moved to [aurelia/ux-components #22](https://github.com/aurelia/ux-components/issues/22) via [**ZenHub**](https://www.zenhub.com/)
