### ISSUE TITLE
CSS ${} theming

### ISSUE THREAD

**Issue by inhuman-programmer** [aurelia/ux#12]
I use visual studio and the main problem that I came across when developing is using ${} syntax in CSS, what causes red underlines suggesting incorrect syntax. Is there any extension for vs code to fix this? Thanks.

**Comment by khuongduybui** [comment]
There's already an official Aurelia VSCode extension, which ships with a custom Aurelia HTML syntax. Perhaps we can add a custom Aurelia CSS syntax to the extension as well?

https://github.com/aurelia/vscode-extension/

**Comment by EisenbergEffect** [comment]
I'm going to close this and open an issue on the vs code plugin. I'll try to talk to someone on the VS tools team at Microsoft about adding support for this in the VS Aurelia plugin.
