### ISSUE TITLE
ux-rich-text-editor

### ISSUE THREAD

**Issue by ben-girardet** [aurelia/ux#125]
What about a rich text editor in Aurelia UX. Is it a good idea or should it not be part of such a library ?

And if yes, to what degree should it or could it depend on other libraries? I've seen that most components have no dependencies except those on other aurelia modules. The datepicker depends on moment which is fair enough and moment is a widespread and maintain library.

For a rich text editor, what would be the best approach? 
- using another well done rich text editor and embed it inside an Aurelia UX component ?
- not using another rich text editor and doing everything in the component ?
- if we should use another module, which one (or which ones) ?

**Comment by EisenbergEffect** [comment]
For now, I'd saw this is out of scope, since there are a lot of great 3rd party editors that should integrate fine with Aurelia.
