### ISSUE TITLE
Global Style Engine

### ISSUE THREAD

**Issue by ZHollingshead** [aurelia/ux#129]
**Current behavior:**
All base css variables and UX properties are added to the head in separate style tags.

![image](https://user-images.githubusercontent.com/22172935/34265725-5ee7149e-e63c-11e7-8ff0-9d8c7a58edc8.png)

* **What is the expected behavior?**

For all global styles to be in a central managed style tag.

* **What is the motivation / use case for changing the behavior?**

Currently trying to locate styles by inspecting the document is very difficult, akin to a game of hide and seek. A single style tag such as the following would be much easier.

```html
<style type="text/css" id="aurelia-ux/core">
/* reset css here */

/* root theme variables here */
/* swatch variables here */

/* default button theme here */
/* ... */
</style>
```

**Comment by EisenbergEffect** [comment]
Yes, I'd love to improve this.
