### ISSUE TITLE
Arbitrary selector names in devtools

### ISSUE THREAD

**Issue by llicht** [aurelia/ux#13]
**I'm submitting a feature request**

* **Library Version:**
0.1.14

* **Browser:**
Chrome 54 & Firefox 49

**Current behavior:**
CSS selector names like "styles.some-descriptive-selector-name" are converted by Aurelia UX to arbitrary names like ".node_au_ux_12" and ".base_node_au_ux_13", and these are what's shown in the browsers' devtools. (In the above browser versions, at least)

**Expected/desired behavior:**
It would be better if Aurelia UX were to keep the selector names as close to the original as possible.
For example, the above CSS selector could be converted to something like ".au-ux-some-descriptive-selector-name", adding a number prefix/suffix if the class name is not unique.

**Comment by EisenbergEffect** [comment]
We can change the format of the name, but we do need to always attach a unique id onto it since we cannot assume there isn't foreign css on the page (or another instance of the same app) that might conflict.

**Comment by llicht** [comment]
I'm sorry - I just realized this already works correctly. (node & base_node were my selector names - I'm not sure how I missed this before)
