### ISSUE TITLE
Two Way Binding for checked property

### ISSUE THREAD

**Issue by ben-girardet** [aurelia/ux#144]
https://github.com/aurelia/ux/blob/d8b9639653ec76ca4419874f0fdbe58eb9126f9e/packages/switch/src/ux-switch.ts#L16

Seems that the Binding Engine binds the `checked` property in one-way by default. I suggest to explicitly decorate this property with two-way binding:

`@bindable({ defaultBindingMode: bindingMode.twoWay })`

**Comment by bigopon** [comment]
@ben-girardet Thanks for notifying, it will be resolved by #141
