### ISSUE TITLE
Add fallback properties to CSS to ensure components still work in browsers that do not support CSS Variables

### ISSUE THREAD

**Issue by ZHollingshead** [aurelia/ux#149]
We should include fallback CSS properties to ensure that all components will still display even in browsers that do not support CSS Variables.

**Comment by Alexander-Taran** [comment]
could it be done with a "flag" like compat-layer?
could those be built as another css to require?
It's a lot of added weight "just for ie"
https://caniuse.com/#feat=css-variables

**Comment by ZHollingshead** [comment]
I would not be opposed to that, but each component would need the compat layer added, so an extra CSS file for each component.

**Comment by fkleuver** [comment]
Or have a single javascript component handle the fallback by appending a `style` element?

**Comment by Alexander-Taran** [comment]
I was thinking define style `if defined 'compat'  import css_fallback`.. if that possible

**Comment by ZHollingshead** [comment]
@fkleuver So I do not feel that having a separate component handle this would be the right approach.

@Alexander-Taran If we can find a lightweight method to add in fall back styles that would be good, lets open a new issue to discuss this and potential ways to handle this, this issue was meant to simply add the appropriate css fallback properties.

**Comment by Alexander-Taran** [comment]
@ZHollingshead sure.
It's your issue after all (-:
