### ISSUE TITLE
Date/Time Picker: After changing locale to Italian, Week Starts from 'Monday' but Column still says 'Sunday'

### ISSUE THREAD

**Issue by askdanserbanoiu** [aurelia/ux#150]
**I'm submitting a bug report**

* **Library Version:**
0.7.1 (updated to latest just now actually)

* **Operating System:**
Windows 10

* **Node Version:**
8.4.0

* **NPM Version:**
5.3.0

* **Webpack**
Latest

* **Browser:**
Chrome Latest

* **Language:**
TypeScript 

**Current behavior:**
Changing locale to Italian updates Datepicker's locale so the Datepicker will start for every week from Monday and have also the Texts in Italian. But the column names are still in wrong order, still starting from Sunday (although translated in Italian).

To be more specific the actual value of the date starts from Monday for every week, just the names are wrong as they associate for ex. still a Sunday column name to a Monday Date value. You can see an example of what I'm saying in the picture below.

![cattura](https://user-images.githubusercontent.com/32792904/36590458-0777110c-188f-11e8-8a13-87e19d452e4d.PNG)

**Expected/desired behavior:**
If the datepicker starts from Monday the column description should say Monday.

**Comment by bigopon** [comment]
solved by #321
