### ISSUE TITLE
UX Checkbox does not currently databind correctly

### ISSUE THREAD

**Issue by ZHollingshead** [aurelia/ux#154]
**I'm submitting a bug report**

* **Library Version:**
0.7.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
9.6.1

* **NPM Version:**
5.6.0

* **Browser:**
all 

* **Language:**
TypeScript 2.7.2

**Current behavior:**
The UX Checkbox component does not currently function in the `app-ux-showcase` application when built from the master branch. The component shows the state change but the bindings do not appear to work.

![image](https://user-images.githubusercontent.com/22172935/37156754-a2c93014-22ac-11e8-87be-bea7fc9cdd4d.png)

**Expected/desired behavior:**
Databinding to work correctly.

**Comment by ZHollingshead** [comment]
@bigopon you are more familiar with the updated components, can you take a look?

**Comment by ben-girardet** [comment]
Just writing here on top of my head but it seems to me that when I’m using the ux-checkbox component in my projects I’m forced to clearly state a two-way binding for the binding to work. This is not the case for other components like ux-input which default to two-way binding by itself.
