### ISSUE TITLE
UX Select --ux-theme-select-foreground naming error

### ISSUE THREAD

**Issue by martinkraan** [aurelia/ux#161]
**I'm submitting a bug report**

* **Library Version:**
0.8.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.7.2

* **NPM Version:**
4.1.2

* **JSPM OR Webpack AND Version**
webpack 3.5.5

* **Browser:**
all

* **Language:**
all

**Current behavior:**
The name of the css variable --ux-theme-select-foreground is wrong.

**Expected/desired behavior:**

* **What is the expected behavior?**
It should be --ux-theme--select-foreground

* **What is the motivation / use case for changing the behavior?**

**Comment by bigopon** [comment]
fixed by #163

**Comment by bigopon** [comment]
@martinkraan Thanks for the bug report 👍
