### ISSUE TITLE
Switch all component build to rollup

### ISSUE THREAD

**Issue by bigopon** [aurelia/ux#162]
With #147 in place, and incoming new way to register global resources via https://github.com/aurelia/framework/pull/858 , it's now possible to distribute every ux package in a single file., and it's more desirable to to do, for build pref, runtime startup perf, size reasons.

Rollup is a good bundler for this, and it will also make the build setup very simple.

 Thoughts ? @ZHollingshead @EisenbergEffect

**Comment by ZHollingshead** [comment]
I like the idea of this. Is this one file overall per component or one file per format? (i.e. one for AMD, one for CommonJS, one for system)

**Comment by bigopon** [comment]
it will be one file overall per module type (amd, commonjs ...) , like what we did with core.

**Comment by ZHollingshead** [comment]
Alright, I think this will be fine then. We should have the packages and core synced up anyways as far as the build method.

**Comment by EisenbergEffect** [comment]
@bigopon This can be closed right?

**Comment by bigopon** [comment]
Yes, Rollup, while gives a lot of benefits related to distribution, limits the consumption of a component library that distributes custom element (ex: CSS autoprefixing).
Closing this as we went for the middle way.
