### ISSUE TITLE
Not all js files are bundled via aurelia-cli

### ISSUE THREAD

**Issue by llicht** [aurelia/ux#17]
**I'm submitting a bug report**

* **Library Version:**
0.1.14

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **NPM Version:**
3.10.9

**Current behavior:**
When using Aurelia-cli to bundle aurelia-ux (e.g. in the same way app-ux-showcase does), the following js files end up not being bundled but are still attempted to be loaded by aurelia-ux at runtime:
ux-button.js
design-attributes.js
paper-ripple.js
paper-wave.js
element-rect.js

(Usually, the browser ends up finding them in node_modules, so the issue is less noticable then.)

This reproduces both in app-ux-showcase and any other app that uses aurelia-ux via Aurelia-cli in the same manner.

Adding "./button/ux-button.js" to "resources" in aurelia.json is a workaround. (It appears to take in all of the above automatically)

**Expected/desired behavior:**
The browser should not need to load files from node_modules to run a Aurelia-ux based app.

* **What is the motivation / use case for changing the behavior?**
Causes errors when node_modules isn't accessible by browser.

**Comment by AStoker** [comment]
Not sure of this solves your problem, but according to the build commands for the UX repo, you need to run `npm run build` That should build all your files.

**Comment by AStoker** [comment]
Assuming you have the Aurelia UX project in the same directory as your App-UX-Showcase project, a list of instructions to build UX components and bring them over to the showcase to test would be:  
- UX: `npm run build`  
- Showcase: `au update-ux`  
- Showcase: `au run`  

This is currently what I'm doing, and appears to work fine for me.

**Comment by llicht** [comment]
To clarify, this issue doesn't prevent app-ux-showcase (or other aurelia-ux apps) from running normally, it just causes the browser to depend on files in node_modules.
To see this, you can temporarily rename node_modules to something else (**after** doing 'au run', of course) and see that the browser is no longer able to launch app-ux-showcase.

I'm reporting the issue because once you try to use an AureliaUX-using app in an environment where the browser can't access node_modules, this issue causes an error.

**Comment by AStoker** [comment]
Thanks for clarifying. I'm able to reproduce this. Do you have any ideas as to why this would be happening? A PR for a fix would be awesome!

**Comment by EisenbergEffect** [comment]
I'm aware of the issue. It has to do with the Aurelia-UX index not exporting everything yet so the full code can't be traced. It will be fixed at the library level. It should also be fixable at the app level using resources.

**Comment by khuongduybui** [comment]
@EisenbergEffect How do I fix this "at the app level using resources"? I'm bundling node_modules/aurelia-ux/* along in my distribution for the time being but a less intrusive way is highly appreciated.

**Comment by khuongduybui** [comment]
Never mind, I just figured out that we can add ".js" files into "resources" array as well.
