### ISSUE TITLE
Normalize.css bug when using Aurelia UX with Webpack on Cordova

### ISSUE THREAD

**Issue by ben-girardet** [aurelia/ux#171]
**I'm submitting a bug report**

* **Library Version:**
0.10.1

**Please tell us about your environment:**
* **Operating System:**
ios web app built with Cordova

* **JSPM OR Webpack AND Version**
webpack 4.8.3

* **Browser:**
 iOS XX UIWebView

* **Language:**
TypeScript X.X

**Current behavior:**
When building the app, the AureliaUX styles are not taken into account (all the root CSS vars). This comes from the fact that AureliaUX creates a wrong line `[object Object]` in the styles section (see below).

<img width="552" alt="capture d ecran 2018-05-17 a 10 34 39" src="https://user-images.githubusercontent.com/4275071/40166291-79b8a9fe-59be-11e8-84df-f18d5aba4ed2.png">

When building the app for the web `au run --watch` the styles work properly (no problem). I've tested in Chrome and Safari (MacOS) and it works correctly.

However, when running the same web app inside a cordova project, I've got this line coming in the styles sections. What's strange is that the following <styles> tag contains the proper normalize.css code, but for some reason, only in this environment, AureliaUX writes this wrong object line in the AurliaUX styles tag.

Note also that I've used the same code source in an AureliaCLI with RequireJS project and here also: no problem. Only when building with AureliaCLI and webpack  I have the problem. 

I've looked a little bit at the code but have no idea where this come from. Any idea?

**Comment by ben-girardet** [comment]
I currently found a temporary fix by deactivating the normalize.css script when calling @aurelia-ux/core library:

```
.plugin(PLATFORM.moduleName('@aurelia-ux/core'), (config) => {
  // do nothing, so no call to defaultConfiguration() nor cssNormalize()
})
```

**Comment by bigopon** [comment]
This has been fixed by https://github.com/aurelia/ux/commit/1a38f1439f88d30e036a74f40019da1eda317425. Thanks to @MaximBalaganskiy
