### ISSUE TITLE
UX Radio component does not apply name attribute to input element

### ISSUE THREAD

**Issue by ZHollingshead** [aurelia/ux#179]
* **Library Version:**
0.12.0

* **Browser:**
all

* **Language:**
all

**Current behavior:**
When the `ux-radio` element has a `name` attribute, this is not passed down to the inner input element, causing issues when tabbing through a form.

**Expected/desired behavior:**
When the `ux-radio` component has a `name` attribute applied it should remove the attribute and value from the `ux-radio` element and apply them to the inner `input` element.

**Comment by EisenbergEffect** [comment]
Feel free to send PR :)

**Comment by ZHollingshead** [comment]
Already done and being batched in with a lot of other changes. Be looking for that in the next day or two.

**Comment by EisenbergEffect** [comment]
Sounds good!
