### ISSUE TITLE
[question] Mobile apps

### ISSUE THREAD

**Issue by inhuman-programmer** [aurelia/ux#18]
When this ux came out, I was surprised that I will finally be able to make mobile apps with aurelia, but there are no examples showing aurelia ux on mobile.

Does anyone know where to find any examples of it working with Cordova/...?

**Comment by shannonhorn** [comment]
very sorry but you'll have to wait a little longer. it's being developed now and is not at that level yet.

**Comment by EisenbergEffect** [comment]
I'll add a few more things to our master feature list to track this. We don't have the actual Cordova piece in place yet, only the detection of the presence of Cordova which we then use to detect the native platform.
