### ISSUE TITLE
Multiple versions of @aurelia-ux/core found:

### ISSUE THREAD

**Issue by stuartbale** [aurelia/ux#201]
**I'm submitting a bug report**

* **Library Version:**
0.16.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10.16.0

* **NPM Version:**
6.9.0

* **JSPM OR Webpack AND Version**
webpack 4.34.0

* **Browser:**
all

* **Language:**
TypeScript 3.5.1

**Current behavior:**
I have followed the instructions in a new Aurelia project, to add aurelia-ux.
When building the project, there are various warnings:
WARNING in @aurelia-ux/core
  Multiple versions of @aurelia-ux/core found:
    0.16.0 ./~/@aurelia-ux\core
    0.4.0 ./~/@aurelia-ux\slider/~/@aurelia-ux\core

WARNING in aurelia-dependency-injection
  Multiple versions of aurelia-dependency-injection found:
    1.3.1 ./~/@aurelia-ux\slider/~/@aurelia-ux\core/~/aurelia-dependency-injection
    1.4.2 ./~/aurelia-dependency-injection

WARNING in aurelia-metadata
  Multiple versions of aurelia-metadata found:
    1.0.3 ./~/@aurelia-ux\slider/~/@aurelia-ux\core/~/aurelia-metadata
    1.0.6 ./~/aurelia-metadata

WARNING in aurelia-pal
  Multiple versions of aurelia-pal found:
    1.3.0 ./~/@aurelia-ux\slider/~/@aurelia-ux\core/~/aurelia-pal
    1.8.2 ./~/aurelia-pal

It appears to me that the slider control has invalid and/or unneeded references

**Expected/desired behavior:**
When adding aurelia UX to a new Aurelia project, it should not have warnings when building.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
It appears to be a bug

**Comment by stuartbale** [comment]
OK - I think I can see the issue. It appears that the slider component is including it's own node_modules folder as per the attached image. I'm hoping this is something that is easily fixed.

Manually deleting the node_modules removes the warning, and the app runs correctly.
![Screen Shot 2019-06-21 at 1 35 52 PM](https://user-images.githubusercontent.com/1775472/59892044-a7216900-942b-11e9-8cd0-c37b14bb4638.png)

**Comment by bigopon** [comment]
This should be solved by recent work from @MaximBalaganskiy that put `@aurelia-ux/core` as peer dependency. Thanks for creating this issue.
