### ISSUE TITLE
Component theming and CSS consistency (discussion)

### ISSUE THREAD

**Issue by ben-girardet** [aurelia/ux#231]
I open this discussion to see if we can improve theming and CSS consistency across components.

As a start of discussion I would like to take `ux-input` as an exemple (version 0.17.0).

Currently the declared theme properties are:

```
import { UxTheme } from '@aurelia-ux/core';

export class UxInputTheme implements UxTheme {
  public themeKey = 'input';

  public foreground: string;
  public foregroundLabel: string;
  public background: string;
  public backgroundHover: string;

  public fontSize: string;
  public letterSpacing: string;
  public labelFontSize: string;
  public labelLetterSpacing: string;

  public border: string;
  public borderHover: string;
  public borderFocus: string;
  public borderRadius: string;
  public borderBottom: string;
  public borderBottomHover: string;
  public borderBottomFocus: string;

  public diabledForeground: string;
  public disabledBackground: string;
  public disabledBorder: string;

  public error: string;
}
```

Not all properties are then used in the `.css` file. For exemple, `borderHover` or `borderBottomHover` are not. In fact, regarding `:hover` state, the only current CSS styling is: 

```
.ux-input:hover {
  background-color: #00000027;
  background-color: var(--aurelia-ux--input-background-hover, #00000027);
}
```

Which uses the `backgroundHover` theme property.

My concern right now are:

* For people using the library: it's quite confusing to find the list of theme properties when not all of them effectively affect the component. With Typescript typing, I find that it's a great benefit to have properly declared theme files so that users can quickly find out what properties can be styled.
* For library contributors: it would be helpful to clarify the conventions that we want to follow (see question below)

Where to go from here ?

1. Should we start by removing useless theme properties to improve usability ?
2. I know that when Aurelia first started working towards this UX library (Aurelia Interface), the goal was to be able to adapt the styling according to the platform where the application is running (as described on the wiki https://github.com/aurelia/ux/wiki/Component-Creation-Process). At this stage all components follow quite well the material design guidelines but I've not seen how the host detection works in order to switch from one design language to another. Any doc in this regards? Is it still the goal ? Or is it something that is secondary and planned to be implemented once we have a full set of components following Material Design guidelines?

I would appreciate feedbacks from Core Team Members regarding these questions as it would help me see where we are going with Aurelia UX and how to contribute in the future.

**Comment by EisenbergEffect** [comment]
My personal opinion is that we should remove the unused properties for now. They can be added back if needed when a second design system is added.

I don't think we've got any platform detection currently. We do want to add iOS styles and also Fluent Design, but wanted to get a pretty full-featured Material implementation first.

**Comment by serifine** [comment]
I think we should remove any properties that are not used. At the same time, however, I think we should ensure the properties we are currently using make sense as well.

I don't think the theme files have to be very comprehensive and encompass every css property because I have discovered over time the CSS structure being so flat allows a user to easily customize the look and feel of the components if they need to.

**Comment by EisenbergEffect** [comment]
Great point @serifine! I think my initial idea was that these properties should primarily support the design systems, so that switching from material, to ios etc. was just a matter of choosing a preset of variables. We won't know exactly what all those need to be until we implement a second design system. So, perhaps for now, we should keep things simple.

@serifine Do you feel that you have a sense of what the core variables we need to target are?

**Comment by serifine** [comment]
I think, off the top of my head, the only one that actually needs to change is the border color to get it to make sense just by reading the name. Other than that, I'm not sure which properties need to stay, and which need to go.

**Comment by ben-girardet** [comment]
I've started to work on this and would like to publish a WIP PR soon so that we can see how it could look like in the code.

I've been working on the `ux-button` component with these goals in mind:

* **relevency**: making sure that theme properties are usefull and all declared properties are used
* **consistency**: making sure they all make sense
* **material design**: fit to material design guidelines

I've also put together a testing page (in the dev app provided by @bigopon) and it really helps to test out component with all possible variables.

Before to do the last bits, I'm seeking your opinions to see if it would be better to "_really keep things simple_" or if we go for "_having many options_"

In the case of the `ux-button`, if we want to be relevant and consistent, here is what it should look like (trying to keep all the previously possible options):

```
export class UxButtonTheme implements UxTheme {
  public themeKey = 'button';

  public background?: string;
  public foreground?: string;

  public accentBackground?: string;
  public accentForeground?: string;

  public textBackground?: string;
  public textForeground?: string;

  public accentTextBackground?: string;
  public accentTextForeground?: string;

  public outlineForeground?: string;
  public accentOutlineForeground?: string;

  public flatBackground: string;
  public flatForeground: string;

  public accentFlatBackground?: string;
  public accentFlatForeground?: string;

  public backgroundDisabled?: string;
  public foregroundDisabled?: string;

  public fontWeight?: string;
  public fontSize?: string;
  public letterSpacing?: string;
  public textTransform?: string;
}
```

My concern are:

* it's a lot of options. Can be useful but also confusing
* it's also a lot to maintain
* and in fact, we should also split the disabled properties to set each button type

So the other option is to cut down the possibilities by using main pairs of background/foreground:(and using each pair across all button types). It would look like:

```
export class UxButtonTheme implements UxTheme {
  public themeKey = 'button';

  public background?: string;
  public foreground?: string;

  public accentBackground?: string;
  public accentForeground?: string;

  public backgroundDisabled?: string;
  public foregroundDisabled?: string;

  public fontWeight?: string;
  public fontSize?: string;
  public letterSpacing?: string;
  public textTransform?: string;
}
```

In ths second scenario, the idea is that we (logically) use the backgrounds and foregrounds for each type, except for outline where the background property is used for border and text.

What is best in your opinion ?

**Comment by ben-girardet** [comment]
The above discussion is about _button types_ and the level of details that we want in the theme regarding the types.

Once this is settled, there will also be the question for the _button states_ (hover, focus, active). 

Currently (if I understood correctly) these states are handled with a grayish color, which is smart because it works in most cases without the need to provide (again) theme variables. I suggest to keep it this way even though it's not 100% material design...

The other option that I can think of is using CSS filters to darken or lighten the background color and use it as focus/active color. The challenges here are:

* browser support (what is the current spec about browser target?)
* how to know when to darken and when to lighten the background to properly set the focus or active color

https://caniuse.com/#feat=css-filters

**Comment by ben-girardet** [comment]
The above discussion is about _button types_ and the level of details that we want in the theme regarding the types.

Once this is settled, there will also be the question for the _button states_ (hover, focus, active). 

Currently (if I understood correctly) these states are handled with a grayish color, which is smart because it works in most cases without the need to provide (again) theme variables. I suggest to keep it this way even though it's not 100% material design...

The other option that I can think of is using CSS filters to darken or lighten the background color and use it as focus/active color. The challenges here are:

* browser support (what is the current spec about browser target?)
* how to know when to darken and when to lighten the background to properly set the focus or active color

https://caniuse.com/#feat=css-filters

**Comment by EisenbergEffect** [comment]
Let's start with the button types PR. When it's ready we can all have a look and see how it plays out in practice. Then we can try to deal with the states in a second pass.

**Comment by ben-girardet** [comment]
Yes I agree that the state question is for later. At he moment I’m especially interested to have your opinions about the background/foreground pairs of properties (https://github.com/aurelia/ux/issues/231#issuecomment-558320657)

If you already have any thoughts let me know... I’ll post a first PR in a few hours.

**Comment by EisenbergEffect** [comment]
I definitely like the proposal for the property pairs. It's much simpler and cleaner if we can make it work for the different button types. I'd love to see a PR for that so we can talk over the details and also get @serifine involved for review and to see if we want to propagate that to the rest of the controls where appropriate.

**Comment by ben-girardet** [comment]
Forgot to mention that a first draft PR is ready: #232

Comments or review are welcome to help shape the continuation of the work.
