### ISSUE TITLE
UX-Button Icon Type

### ISSUE THREAD

**Issue by khuongduybui** [aurelia/ux#25]
Simply ```<ux-button type="flat fab"/>``` should give me a round (fab) button with no box shadow (flat).
This can be used for [mini secondary actions inside a list](https://material.google.com/components/lists.html#lists-actions).

Here's how I implemented it in my own project (which consumes aurelia/ux):
```
ux-button
  button.flat.fab
    margin 0
    padding 0
    min-width auto
    box-shadow none
```

**Comment by moodledan** [comment]
Material Design has guidelines for the use of [shadows/elevation](https://material.google.com/material-design/elevation-shadows.html#) so I'd be tempted to include it (not include it) in the same way as swatches. 

Pseudo code used below to demonstrate: 

Perhaps a `shadows.ts` containing:

```
export const shadows = {
  depth_0: ' none',
  depth_1: '0 2px 2px 0 rgba(0,0,0,0.14),0 1px 5px 0 rgba(0,0,0,0.12),0 3px 1px -2px rgba(0,0,0,0.2)',
  depth_2: '0 4px 5px 0 rgba(0,0,0,0.14),0 1px 10px 0 rgba(0,0,0,0.12),0 2px 4px -1px rgba(0,0,0,0.3)',
  depth_3: etc ...
};
```

Then update `material-design.ts` with:

```
import {Design} from './design';
import {swatches} from '../colors/swatches';
import {shadows} from '../colors/shadows';

export class MaterialDesign implements Design {
  public type = 'material';

  public shadow_elevation_none = shadows.depth_0;
  public shadow_elevation_1 = shadows.depth_1;
  public shadow_elevation_2 = shadows.depth_2;

}
```

.. finally in you could then update the `ux-button-theme.css` to make use of these values:

styles.button.fab {
  border-radius: 50%;
  overflow: hidden;
  transition: box-shadow 0.2s cubic-bezier(0.4, 0, 0.2, 1);
  transition-delay: 0.2s;
  box-shadow: ${$design.shadow_elevation_2};
}

**Comment by EisenbergEffect** [comment]
Bingo! Sounds great. Would you mind submitting a PR?

**Comment by moodledan** [comment]
Sure, I'll mock it out over the next couple of days.

**Comment by moodledan** [comment]
See PR here: https://github.com/aurelia/ux/pull/26

**Comment by EisenbergEffect** [comment]
Thanks! We'll take a look shortly.

**Comment by khuongduybui** [comment]
So, assuming the PR is approved, my flat fab button style will now look like this?
```
ux-button
  button.flat.fab
    margin 0
    padding 0
    min-width auto
    box-shadow ${$design.elevation2dp}; 
```

**Comment by ZHollingshead** [comment]
It does not look like this is supported functionality yet. This would be easy to implement, though I do have a couple concerns. 

Flat by Google's Material guidelines referring to a button does not mean a button has no shadow, it means it has no background either, basically just a clear button.
>Flat buttons are text-only buttons. 
>They may be used in dialogs, toolbars, or inline.
>They do not lift, but fill with color on press.
[Material Design Guidelines - Buttons](https://material.io/guidelines/components/buttons.html)

Another point is going by Google's material design guidelines, a flat FAB does not appear to be part of its intended usage based on its description.

> Shaped like a circled icon **floating above the UI**, it changes color upon focus and lifts upon selection. When pressed, it may contain more related actions.
[Material Design Guidelines - Floating Action Button](https://material.io/guidelines/components/buttons-floating-action-button.html)

**Comment by ZHollingshead** [comment]
As a follow up to this, there is actually a section that directly talks about flat fabs.

>Don't.
>Without a shadow, nothing indicates that the floating action button is separate from the background surfaces.
[Material Design Guidelines - Shadows](https://material.io/guidelines/material-design/elevation-shadows.html#elevation-shadows-shadows)

It goes as far as to list the exact heights that should be used for its shadows.

**Comment by ZHollingshead** [comment]
I pondered on this for a while and I think what would be helpful is if we had an icon type. So a button that would be only an icon but flat as you said. Doing this that way would keep us from using a FAB in a way that goes against the Material Guidelines.

I am thinking simply:
``` html
<ux-button type="icon">
    <!-- your icon here -->
</ux-button>
```

This would go well with adding Icons to UX. We could potentially add an attribute to help us here when we have an official icon implementation to do something like 
``` html
<ux-button type="icon" icon="add"></ux-button>
```

@EisenbergEffect what are your thoughts? I think this would be a good solution that would have immediate use cases and pretty easy to put in.

**Comment by EisenbergEffect** [comment]
Let's go for it :)
