### ISSUE TITLE
Already extracted normalize.css is being added to global styles

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/ux#260]
**I'm submitting a bug report**

* **Library Version:**
0.20.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
12.16.2

* **NPM Version:**
6.14.4

* **Webpack Version**
webpack 4.42.1

* **Browser:**
all

* **Language:**
TypeScript 3.8

**Current behavior:**
`ux-configuration.ts` module loads `@aurelia-ux/core/styles/normalize.css` into global styles tag. 
https://github.com/aurelia/ux/blob/ed989f92fb10948f086e92a3665814444f9e2a45/packages/core/src/ux-configuration.ts#L29

But because webpack extracted it already an empty object gets stringified which results in invalid style tag. This invalidates consequently added styles.
The bug can be observed at https://ux.mintello.com/.

**Expected/desired behavior:**
The style is not added when it has been previously extracted by the loader.

* **What is the motivation / use case for changing the behavior?**
Allow components adding their own global styles.

**Comment by bigopon** [comment]
We still need to include this css module, so we probably just need to tweak
```ts
PLATFORM.moduleName('./styles/normalize.css');
```
to
```ts
PLATFORM.moduleName('text-loader!./styles/normalize.css');
```
maybe?

**Comment by MaximBalaganskiy** [comment]
Duplicate of #171
