### ISSUE TITLE
Expansion panel component

### ISSUE THREAD

**Issue by swalters** [aurelia/ux#262]
Are there any immediate plans to implement an expansion panel similar to https://material.angular.io/components/expansion/examples or https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/collapsible/basic-use ?

**Comment by bigopon** [comment]
@swalters theres not an immediate plan, but contribution is welcome. Unless @ben-girardet already got this going

**Comment by MaximBalaganskiy** [comment]
@swalters @bigopon do you expect the panel to be pre-styled or just provide default animation and leave the rest to a consumer?

**Comment by swalters** [comment]
Looking at other libraries, I see two general approaches

**Separate component**
Angular Material uses a separate component that includes styling.  I think this would be easy to use but you are at the mercy of the components layout and styling. https://material.angular.io/components/expansion/overview

**Enable expansion of list items**
Aurelia Materialize Bridge uses an attribute and other css classes to make list items expandable
https://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/collapsible/expandable
Vue Material adds an expandable property to the list component. https://vuematerial.io/components/list


In my desktop focused application, expandable sections are used in a sidenav list (the Materialize and Vue Material approach) and used on forms to hide advanced options and give the form a cleaner appearance (the ng material approach).  

I'm open to either approach but I think a separate component would be easiest to utilize as long as it worked well with sidenav

**Comment by MaximBalaganskiy** [comment]
![expandable](https://user-images.githubusercontent.com/3712700/81756344-cff89400-94fe-11ea-9852-ab036d928572.gif)
Will something like this do?

**Comment by bigopon** [comment]
Maybe we can try with a separate component first, to see how it works and later refactor the core logic of the expand/collapse into an attribute, and then use it for general purposes, same path taken for ux-choice & ux-choice-container

**Comment by MaximBalaganskiy** [comment]
@swalters you can try it here https://github.com/MaximBalaganskiy/ux/tree/expandable

**Comment by MaximBalaganskiy** [comment]
@bigopon I think it is hard to extract it to an attribute - there is internal component structure which I would hate to replicate if I was a consumer

**Comment by bigopon** [comment]
We can still insist some basic structure of the dom to be used with attribute I think. But maybe let's focus on that later? Having the component in first sounds awesome enough to me ❤️

**Comment by swalters** [comment]
@MaximBalaganskiy That looks perfect.  I'll try it out soon in my app.  I hope we see this and the other components you've developed merged soon.

**Comment by swalters** [comment]
@MaximBalaganskiy Looks good to me.  Easy to use in my nav sidebar and in edit forms
