### ISSUE TITLE
ux-icon in disabled button accepts clicks

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/ux#280]
**I'm submitting a bug report**

* **Library Version:**
0.20.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
12.16.2

* **NPM Version:**
6.14.4

* **JSPM OR Webpack AND Version**
webpack 4.42.1

* **Browser:**
all

* **Language:**
TypeScript 3.9

**Current behavior:**
`ux-icon` in disabled button accepts clicks

**Expected/desired behavior:**
* **What is the expected behavior?**
button is disabled completely

* **What is the motivation / use case for changing the behavior?**
using icons in buttons

**Comment by ben-girardet** [comment]
Hi @MaximBalaganskiy 

Did you place the `click.delegate()` on the `<ux-button/>` or the `<ux-icon/>` ?

**Comment by MaximBalaganskiy** [comment]
on the button

**Comment by MaximBalaganskiy** [comment]
ux-icon click event must be bubbling to the ux-button

**Comment by ben-girardet** [comment]
Yes, that would be what is happening. We might be able to handle this with CSS with something like:

```css
.ux-button--disabled * {
  pointer-events: none;
}
```

what do you think ?

**Comment by MaximBalaganskiy** [comment]
this fixed the issue
