### ISSUE TITLE
select drops outside the window

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/ux#284]
**I'm submitting a bug report**

* **Library Version:**
0.20.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
12.16.2

* **NPM Version:**
6.14.4

* **JSPM OR Webpack AND Version**
webpack 4.42.1

* **Browser:**
all

* **Language:**
TypeScript 3.9

**Current behavior:**
When select is close to the window botton the dropdown drops outside the window

**Expected/desired behavior:**
* **What is the expected behavior?**
Either scroll is enabled or dropdown moves above the element

* **What is the motivation / use case for changing the behavior?**
Support different select positions on the page

**Comment by MaximBalaganskiy** [comment]
To be fair, NG doesn't adjust either :)

**Comment by bigopon** [comment]
Well yes, this is what the positioning service is for. Will fix later, or happily taking PR 😁

**Comment by MaximBalaganskiy** [comment]
Same thing happens now when a dropdown goes over the right edge
![image](https://user-images.githubusercontent.com/3712700/84248200-752d7900-ab4c-11ea-9d60-9106e41fad38.png)
