### ISSUE TITLE
BUG: Not all packages (v.0.24.0) were published properly on npmjs registry

### ISSUE THREAD

**Issue by glyad** [aurelia/ux#323]
I'm submitting a bug report

Library Version:
latest

Operating System:
macOS 10.15.5 Catalina

Node Version:
14.15.0

NPM Version:
6.14.7

Webpack
Latest

Browser:
Chrome Latest

Language:
TypeScript 3.9.5

Seems likes as not all of the packages are published properly on npmjs.com:
1. @aurelia-ux/components
2. @aurelia-ux/positioning
3. @aurelia-ux/textarea
4. @aurelia-ux/switch
5. @aurelia-ux/radio
6. @aurelia-ux/select
7. @aurelia-ux/sidenav
8. @aurelia-ux/progress
9. @aurelia-ux/slider

It's despite the fact that versions of all those packages were updated in corresponding package.json files.

**Comment by EisenbergEffect** [comment]
Republished all packages at 0.25.0.
