### ISSUE TITLE
ux-input

### ISSUE THREAD

**Issue by ZHollingshead** [aurelia/ux#33]
I am interested in working on this control.

I started the process of switching one of our applications where I work over to Aurelia and we also plan on implementing the Aurelia UX library. Since I will be developing these controls anyways, I figure I may as well develop them once and contribute to the project instead of developing once, and replacing that work later as the components are implemented in Aurelia UX.

My current list of features I would want to add, simply because we need them are:

Are there any major features that are desired for the base implementation such as a min/max character counter or error labels?

**Comment by EisenbergEffect** [comment]
For some reason the list didn't come through. Can you add that again? We'd love to have you as a contributor!

**Comment by ZHollingshead** [comment]
Interesting, let me add that one more time then.

My current list of features I would want to add, simply because we need them are:
- Minimum and Maximum Character Counter
- Input Labels
- Error Messages
- Input Icons
- Various Input Types (Password, Numeric, Email, Etc.)

**Comment by EisenbergEffect** [comment]
I"d love to have you work on this. Regarding any sort of error messages, I'd want to make sure this integrates nicely with our Aurelia Validation library. For labeling, we need to consider both Material and iOS styles. I would like to keep the label as something separate that could decorate the control, if possible, in order to provide max flexibilty.

So you should be able to just use

```html
<au-input value.bind="firstName"><au-input>
```

but also something like:

```
<au-field>
  <label>First Name</label>
  <au-input value.bind="firstName"><au-input>
</au-field>
```

The label would take on the style of the platform.

**Comment by ZHollingshead** [comment]
I was thinking along similar lines. Should we strive to keep the Aurelia Validation library from being a dependency of Aurelia UX?

Also, would the au-field fit more with the Form Layout & Labels feature?

**Comment by EisenbergEffect** [comment]
We don't need to creat a dependency but rather consider how we could plug
in our validation library as part of the design.

**Comment by ZHollingshead** [comment]
I have some basic functionality completed.

``` html
<ux-input class="single-line" value.bind="firstName" min="5" max="10" input-counter></ux-input>
```

Current style classes are: _single-line_ and _full-width_ which are implemented from the Material Design specs. The input-counter attribute just toggles on a counter for the input which can be dynamic to simply give a count, or a characters remaining view if _max_ is defined on the ux-input.

And here are a couple screenshots from the ux-showcase app that I implemented this in.

![image](https://cloud.githubusercontent.com/assets/22172935/23103388/6d58236c-f680-11e6-9db9-45aad81b313d.png)

![image](https://cloud.githubusercontent.com/assets/22172935/23103453/223737c8-f681-11e6-9b1a-df8c39b63b4c.png)


@EisenbergEffect 
Are there any changes to the API you would like to see for what is currently implemented?

**Comment by EisenbergEffect** [comment]
That seems pretty straight forward and easy to use. I don't see the need to make any changes there. Keep up the great work!

**Comment by ZHollingshead** [comment]
For integrating with the validation library, I feel we can just pass in a list of ValidateResult instances, and display the top most error present. If we do that I can have the standard attributes such as minlength, required, etc add to the list internally to display errors as well.

Something like this

```html
<ux-input value.bind="firstName & validateOnBlur" validation-errors.bind="firstNameErrors"></ux-input>
```
![image](https://cloud.githubusercontent.com/assets/22172935/23185102/c83f43d2-f847-11e6-9f49-3205c3641543.png)

I am not sure if that will work to pass in the errors or if there is an easier way, but that is roughly my line of thinking on how we can accomplish that.

**Comment by EisenbergEffect** [comment]
@jdanyow What do you think?

**Comment by jdanyow** [comment]
Here's what's needed to make a custom data-entry component integrate with validation seamlessly:

1. The component should have only one two-way bindable "value" property.
2. `change` events fired by input(s) within the custom element should be re-fired by the custom element.
3. When the custom element loses focus it should fire a `blur` event.

Pretty easy for components like uxinput which have only one `<input>` element:

```js
@inject(Element)
export class UxInput {
  constructor(private element: HTMLInputElement) {}

  change() {
    const event = DOM.createCustomEvent('change', { bubbles: true });
    this.element.dispatchEvent(event);
  }

  blur() {
    this.element.dispatchEvent(DOM.createCustomEvent('blur'));
  }
}
```

**Comment by ZHollingshead** [comment]
Since the change event already bubbles, I did not add that. But I did go ahead and add the blur event. I am doing some code cleanup at the moment but attached some screenshots from the working version used in the showcase at the bottom.

Working Branch: https://github.com/ZHollingshead/ux/tree/ux-input 

Error messages are not automatic, but they are pretty easy to add.

``` html
<ux-input class="form-control" 
          value.bind="firstName & validate"
          validation-errors.bind="firstNameErrors"
          class.bind="firstNameErrors.length ? 'has-error' : ''"
          placeholder="First Name" >
</ux-input>
<ux-input-info>
    <span if.bind="firstNameErrors.length">${firstNameErrors[0].error.message}</span>
</ux-input-info>
```

The input counter style has changed slightly from being a quick attribute to a second component that pairs with UX-Input, mainly to make handling messages easier, and because the same code can be reused on the Text Area component as well. The counter still picks up on the maxlength attribute from the ux-input to determine whether or not it should display the max length total.
``` html
<ux-input value.bind="totalCharactersRemaining"
          view-model.ref="ibicDemo3" 
          maxlength="10">
</ux-input>
<ux-input-info ux-input-counter target.bind="ibicDemo3">
    I am a message or hint
</ux-input-info>
```

Input labels are not implemented, I took another look at the component list and saw there was an item specifically for Form Layout & Labels, so that seemed a bit redundant.

The UX-Input component passes many of the standard attributes through to the input box such as minlength, maxlength, type, etc. The Autofocus attribute actually has a JavaScript implementation that allows the Autofocus attribute to work more than just one time, a limitation I found with the native implementation.


Based on this, do you see any major features I have left out?


Development Images:
![image](https://cloud.githubusercontent.com/assets/22172935/23476942/005e7fe0-fe82-11e6-9f91-810e6db4ae6f.png)

![image](https://cloud.githubusercontent.com/assets/22172935/23477019/39705376-fe82-11e6-9dbe-e460e4b7c928.png)

![image](https://cloud.githubusercontent.com/assets/22172935/23477027/41665fbc-fe82-11e6-8d09-41d12da1f542.png)

![image](https://cloud.githubusercontent.com/assets/22172935/23477038/4b47485c-fe82-11e6-851a-86b462a7c0ba.png)

![image](https://cloud.githubusercontent.com/assets/22172935/23477045/57f71afa-fe82-11e6-9a9f-609cd5ccd96f.png)

**Comment by bsrdjan** [comment]
Regarding validation messages, two questions.

If the empty space below the input field is not created in advance, when validation errors appear, they push the content below the input field down, just like in showcase app input example with Email validation. 

I find it visually disturbing and was thinking about showing just an icon, inside the input field for example, which on user action like click or hover shows a tooltip or dialog with errors, without disturbing the rest of the content. Would something like this make sense and how complicated such adaptations will be, once the ux library is fully implemented? Staying flexible would be great.

**Comment by ZHollingshead** [comment]
I agree being flexible is good. That is why displaying validation is not handled strictly inside of UX. It does happen to have support baked into the `ux-input-info` component to display errors in the same place as the hint text but other than that this functionality is handled outside of UX.

I do not think it would be hard to modify the Validation Renderer I came up with to render an error icon inside of the input, but I think that should be left up to the individual user since the reason for supporting errors underneath was driven by the [Material Design guidelines] (https://material.io/guidelines/components/text-fields.html).

Here is a copy of the Validation Renderer I have been using. I plan on making this easier to access soon when I finish making small tweaks to it.

``` typescript
import { RenderInstruction, ValidateResult } from 'aurelia-validation';

export class UXFormRenderer {
    public render(instruction: RenderInstruction) {
        for (const { result, elements } of instruction.unrender) {
            for (const element of elements) {
                this.remove(element, result);
            }
        }

        for (const { result, elements } of instruction.render) {
            for (const element of elements) {
                this.add(element, result);
            }
        }
    }

    public add(element: Element, result: ValidateResult) {
        if (result.valid) {
            return;
        }

        element.classList.add('has-error');

        const uxField = element.closest('ux-field');

        if (!uxField) {
            return;
        }

        const inputInfoHintText = uxField.querySelector('ux-input-info');

        if (!inputInfoHintText) {
            return;
        }

        const message = document.createElement('span');

        message.className = 'error-text';
        message.textContent = result.message;
        message.id = `validation-message-${result.id}`;

        inputInfoHintText.insertBefore(message, inputInfoHintText.firstChild);
    }

    public remove(element: Element, result: ValidateResult) {
        if (result.valid) {
            return;
        }

        element.classList.remove('has-error');

        const uxField = element.closest('ux-field');

        if (!uxField) {
            return;
        }

        const inputInfoHintText = uxField.querySelector('ux-input-info');

        if (!inputInfoHintText) {
            return;
        }

        const message = inputInfoHintText.querySelector(`#validation-message-${result.id}`);

        if (message) {
            inputInfoHintText.removeChild(message);

            if (inputInfoHintText.querySelectorAll('.help-block.validation-message').length === 0) {
                inputInfoHintText.classList.remove('has-error');
            }
        }
    }
}
```

**Comment by ZHollingshead** [comment]
To add onto this, Icon Handling is still being researched so if it is decided that an icon with errors is a good path to take, then we will need to figure that out before we can implement that. It is something that is on my radar as a couple other items I want to take care of need the icon support.

**Comment by ZHollingshead** [comment]
Documentation on binding to the disabled attribute needs to be improved.

**Comment by ZHollingshead** [comment]
Issue moved to [aurelia/ux-components #18](https://github.com/aurelia/ux-components/issues/18) via [**ZenHub**](https://www.zenhub.com/)
