### ISSUE TITLE
Examples for use with JS?

### ISSUE THREAD

**Issue by trondhindenes** [aurelia/ux#35]
It would be really sweet to have some documentation and/or example apps written in JS.

**Comment by ZHollingshead** [comment]
We could add an example for setting up Angular UX in the [Showcase Application](https://github.com/aurelia/app-ux-showcase) fairly quickly for both Javascript and Typescript. At this point are not any Typescript specific portions of the code that could not be just copied over from what I found. 

I think the following could be added quickly:
- Setup and start using Aurelia UX
- Code examples on accessing the theme, probably on the theme example page

**Comment by lukelarsen** [comment]
I would love that. I'm working on a team where I'm the designer and I work with css primarily. Have an example of this I could try to run with would be great.

**Comment by ZHollingshead** [comment]
I went ahead and setup a demo project here: https://github.com/ZHollingshead/ux-js-example/tree/master

This is a very bare bones setup with no extra features outside of a hello world page that also has a UX Button control added.

To see exactly what is involved to add this to the project look at the following commit: [Add Aurelia UX](https://github.com/ZHollingshead/ux-js-example/commit/ef2fd39c80d8cb5bbf900f2d636afcb6d58bbd18)

To change the theme simply inject AureliaUX into your constructor where you want to do this and then change the theme from there. You can also set the passed in object as a property on the view-model and access it later. For an example take a look at this commit: [Change Theme](https://github.com/ZHollingshead/ux-js-example/commit/b84b97c391f5c9d375d07e0b936f5a3e778f2928)

I will look into wrapping that up into a nicer documentation page for the official demo app.

**Comment by trondhindenes** [comment]
Great, thanks!!

**Comment by Alexander-Taran** [comment]
maybe can be closed..
