### ISSUE TITLE
ux-textarea

### ISSUE THREAD

**Issue by ZHollingshead** [aurelia/ux#36]
Implement the ux-textarea component for Material and iOS design.

- [ ] iOS
- [x] Material  
- [x] Demo/Documentation

**Comment by ZHollingshead** [comment]
@EisenbergEffect I can tackle this, it lines up with the ux-input component.

**Comment by EisenbergEffect** [comment]
Sounds good. FYI I haven't forgotten about your input contribution. Thanks for helping out on this!

**Comment by ZHollingshead** [comment]
I did not figure you had, I saw all the releases from the core Aurelia project so I know you have been very busy.

For this control, I feel the code will be nearly identical to the ux-input component. So do we want it to be its own component or would we like it to take the form of adding an attribute to the ux input component such as `<ux-input multi-line>`.

**Comment by khuongduybui** [comment]
Between adding this as an attribute vs. a separate component, what would be easier if I later want to "upgrade" my <ux-textarea> with "rich-text" or "syntax-highlighting" attributes?

**Comment by ZHollingshead** [comment]
Accessing the base textarea control underneath will be the same in either scenario.

Though with it as a separate control it would ensure that you are always accessing a textarea element without needing to check that there is a `multi-line` attribute attached first.

The more I think about it, it probably is best they be separate components as listed since a couple attributes from the `ux-input` element would not really be valid for a textarea control. Password and Number types being prime examples along with min and max attributes.

**Comment by EisenbergEffect** [comment]
Let's do it as a separate component for now. I like the idea of mapping one-to-one to standard html elements as well. That will make it easier to learn.

**Comment by ZHollingshead** [comment]
Pull request #39 made for this.

**Comment by khuongduybui** [comment]
This issue can be closed now. (Tested by me, good enough 🤣)

**Comment by ZHollingshead** [comment]
This issue will likely stay open since it also encompasses the iOS design which is not yet complete.

**Comment by ZHollingshead** [comment]
Issue moved to [aurelia/ux-components #11](https://github.com/aurelia/ux-components/issues/11) via [**ZenHub**](https://www.zenhub.com/)
