### ISSUE TITLE
<ux-textarea> leaves a closing </template> inside the generated <textarea>

### ISSUE THREAD

**Issue by khuongduybui** [aurelia/ux#41]
I think that's because this tag uses a self-closing signature while HTML5 expects <textarea> to have a separate ending:
https://github.com/aurelia/ux/blob/master/src/textarea/ux-textarea.html#L4

The </template> on line 8 ends up being treated as inside content of <textarea>.
The browser then adds </textarea> and </template> for the non-closing tags.

**Comment by ZHollingshead** [comment]
I have verified this behavior and am fixing it now.

**Comment by khuongduybui** [comment]
Please also note that this bug makes `createTemplateFromMarkup()` (from `aurelia-pal`) throw an error when trying to load `ux-textarea.html` from resources (embedded using `requirejs/text`).
