### ISSUE TITLE
ux-input types

### ISSUE THREAD

**Issue by khuongduybui** [aurelia/ux#45]
**I'm submitting a bug report**

* **Library Version:**
latest

**Please tell us about your environment:**
irrelevant

**Current behavior:**
```
      if (this.type !== 'text' && this.type !== 'password' && this.type !== 'number') {
        this.type = 'text';
      }
```

**Expected/desired behavior:**
* **What is the expected behavior?**
There are a few more types that do not require special rendering: `email`, `url`, `tel`, `search`, etc.

* **What is the motivation / use case for changing the behavior?**
Most browsers have built-in format validation and know what to autocomplete for these input types.

**Comment by khuongduybui** [comment]
```if (['text', 'password', 'number', 'email', 'url', 'tel', 'search'].every((type) => this.type !== type)) {
  this.type = 'text';
}```

**Comment by ZHollingshead** [comment]
This would not be a hard change if we are okay with letting the browser format the input for now.

**Comment by khuongduybui** [comment]
The types I listed are rendered just like a type=text.
There are other types like range, date, month, datetime, datetime-local... They each is rendered differently, which we can add support for gradually. I can take on that task unless you prefer to assign that to yourself. Anyway that's beyond the scope of this issue.

**Comment by verbedr** [comment]
Why do we want to limit the user? If they specify a wrong type the browser will fall back to text anyway. We could also take a more open approach and only reject types that are superseded by other ux controls. 

`if (['button', 'submit', 'reset'].indexOf(('' + this.type).toLowerCase()) > -1) {
    this.type = 'text';
}`

Just my 2 cents ...

**Comment by ZHollingshead** [comment]
I like the idea of being explicit on what is allowed so we do not add restrictions later down the line such as `datetime`, which will have its own component.

@EisenbergEffect what are your thoughts on this?

**Comment by EisenbergEffect** [comment]
I would prefer to be explicit for now, since this library is still in its earlier stages. We can evolve this over time as we determine how we want to handle other types.

**Comment by ZHollingshead** [comment]
@khuongduybui if you want to create a PR for this that would be awesome. Otherwise, I will probably get to this later today.
