### ISSUE TITLE
Take a look https://adarshpastakia.github.io/aurelia-ui-framework/#/inputs/basic

### ISSUE THREAD

**Issue by Ma3yTa** [aurelia/ux#48]
Take a look https://adarshpastakia.github.io/aurelia-ui-framework/#/inputs/basic

**Comment by ZHollingshead** [comment]
This would go great as a comment under #33 or in our [gitter](https://gitter.im/aurelia/Discuss) channel.

Going to go ahead and close this since this is not addressable. Thanks for the suggestions!
