### ISSUE TITLE
[question] CSS Style bindings security

### ISSUE THREAD

**Issue by CasiOo** [aurelia/ux#5]
What security considerations have been made when it comes to allowing bindings in css?

Will there be any default binding encoding, just like we know it from using `${foo}` in html?
Is the developer expected to only bind trusted data?
Is it only allowed to bind property values that will be escaped (difficult to get right)?

There are so many ways of doing attacks through css, so I'm interested in knowing your considerations when it comes to preventing attacks such as Cross Site Scripting.

My suggestion would be to only ever bind trusted data.

**Comment by EisenbergEffect** [comment]
It's definitely up to the developer what they bind. The style engine uses the same binding engine and parser as the rest of Aurelia. The string interpolation logic is just re-used straight from the binding library.
