### ISSUE TITLE
Webpack V2 Compatibility

### ISSUE THREAD

**Issue by RichiCoder1** [aurelia/ux#55]
I'll follow up with personal testing, but is there a general idea of the level of compatibility with 
the new Webpack plugin? It looks like the global resources configuration isn't using `PLATFORM` declarations at the very least, but I'm not sure what other action might need to be taken.

/cc @jods4

**Comment by cluka** [comment]
The Global Resources configuration does work, if by global resources you mean this:
```javascript
﻿import { PLATFORM } from 'aurelia-pal';
export function configure(aurelia) {
  aurelia.globalResources(PLATFORM.moduleName("resources/select2"));
  aurelia.globalResources(PLATFORM.moduleName("resources/timepicker"));
  ...
}
```

You just have to use `PLATFORM.moduleName('modeule')`

**Comment by cluka** [comment]
I have completed my migration form old webpack to the new webpack plugin. And with a bit of tweak, everything works perfectly.

**Comment by RichiCoder1** [comment]
I'm more specifically referring to:
https://github.com/aurelia/ux/blob/master/src/index.ts#L23

> I have completed my migration form old webpack to the new webpack plugin. And with a bit of tweak, everything works perfectly.

Nice! What tweaks if I may ask? Just `PLATFORM.moduleName`-related changes?

**Comment by cluka** [comment]
> Nice! What tweaks if I may ask? Just PLATFORM.moduleName-related changes?

Yes, that's PLATFORM.moduleName-related changes
Ie. for aurelia-bootstrap, and aurelia-dialog, I had to manually specify each required sub-components in my webpack.config.js like this:
```javascript
new ModuleDependenciesPlugin({
      "aurelia-dialog": [ "./ai-dialog", "./ai-dialog-header", "./ai-dialog-body", "./ai-dialog-footer", "./attach-focus" ],
    }),
```
I think this will not be required when all aurelia's plugins implement the PLATFORM.moduleName, but until then...


> I'm more specifically referring to:
> https://github.com/aurelia/ux/blob/master/src/index.ts#L23

Yes that is it,
Basically, it just come to this:
everywhere you use module names like in ie. router configuration, or like in your example - global resources, you just use PLATFORM.moduleName.
