### ISSUE TITLE
Missing script

### ISSUE THREAD

**Issue by AlbertoMonteiro** [aurelia/ux#58]
**I'm submitting a bug report**

* **Operating System:**
Windows [10]

* **Node Version:**
7.8.0

* **NPM Version:**
4.4.4

**Current behavior:**

```
C:\Projetos\ux
λ  npm run test-watch
npm ERR! missing script: test-watch

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alber\AppData\Roaming\npm-cache\_logs\2017-04-17T14_43_23_181Z-debug.log
```

* **What is the expected behavior?**

Run the **test-watch** npm script

**Comment by EisenbergEffect** [comment]
@ZHollingshead I think this is just a typo. Can you confirm?

**Comment by AlbertoMonteiro** [comment]
@EisenbergEffect I am trying to run to see those components visually, how can I walk through for those components in browser?

**Comment by ZHollingshead** [comment]
That is correct. There is no `test-watch` command. Our build commands mirror Aurelia/Validation.

To run tests:
```
npm run test
```
To run tests in watch mode:
```
npm run develop
```

These will not prove very useful though, currently as there is no test directory and therefore no tests to pass or fail.

**Comment by ZHollingshead** [comment]
@AlbertoMonteiro to see the components visually take a look at https://github.com/aurelia/app-ux-showcase

The instructions to get the showcase up and running are in the readme.md on the main page. I hope this helps!

**Comment by AlbertoMonteiro** [comment]
@ZHollingshead I already downloaded this repo, it works fine, but how is the best way to test my new component that I am creating in AureriaUX?
The app-ux-showcase points to npm package, I am working localy.
I am new in aurelia plugin development, so I dont know those best practices.

**Comment by ZHollingshead** [comment]
@AlbertoMonteiro so to develop for both of them here is what I do.

First, make sure your `aurelia-ux` and `aurelia-ux-showcase` folders are in the same directory. Something like:
```
|-Development
  |- Aurelia
    |- ux
    |- app-ux-showcase
```

Once this is done and both projects are set up, when you make new changes run `au update-ux` from the showcase application. This will copy the built aurelia-ux files into the correct npm folder.  

Before you build, make sure you add any html or css files you will be using to the `aurelia_project/aurelia.json` file. To do this, open the `aurelia.json` file and scroll down until you see the following entry.
``` json
{
  "name": "aurelia-ux",
  "path": "../node_modules/aurelia-ux/dist/amd",
  "main": "index",
  "resources": [
    "./button/ux-button.html",
    "./button/ux-button-theme.css",
    "./input/ux-input.html",
    "./input/ux-input-theme.css",
    "./input-info/ux-input-info.html",
    "./input-info/ux-input-info-theme.css",
    "./textarea/ux-textarea.html",
    "./textarea/ux-textarea-theme.css",
    "./form/ux-form.html",
    "./form/ux-form-theme.css",
    "./form/ux-field.html",
    "./form/ux-field-theme.css",
    "./chip-input/ux-chip-input.html",
    "./chip-input/ux-chip-input-theme.css",
    "./chip-input/ux-chip.html",
    "./chip-input/ux-chip-theme.css",
    "./chip-input/ux-tag.html",
    "./chip-input/ux-tag-theme.css",
    "./effects/paper-ripple.css",
    "./checkbox/ux-checkbox.html",
    "./checkbox/ux-checkbox-theme.css"
    // add your files here
  ]
},
```
Once you have done this you can run the following command to run the showcase and see if your added component works.
```
au run
```

**Comment by AlbertoMonteiro** [comment]
thanks @ZHollingshead
