### ISSUE TITLE
App app-ux-showcase fails to build

### ISSUE THREAD

**Issue by adriatic** [aurelia/ux#6]
**I'm submitting a bug report**

* **Library Version:**
major.minor.patch-pre

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.3.1

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
Chrome 54.0.2840.71 m| 

* **Language:**

**Current behavior:**
```

C:\work\aurelia-ux\app-ux-showcase (master) (app-ux-showcase@0.1.0)
λ npm run build
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nik\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.8

npm ERR! missing script: build
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\work\aurelia-ux\app-ux-showcase\npm-debug.log
```

**Comment by EisenbergEffect** [comment]
You will need to use the Aurelia CLI. It should be `au build`.

**Comment by adriatic** [comment]
Are you aware that the [README file](https://github.com/aurelia/ux/blob/master/README.md) says `npm run build`?

**Comment by EisenbergEffect** [comment]
It must be another copy/paste error. Sorry. One moment.

**Comment by EisenbergEffect** [comment]
I don't see it in the showcase app repo. In the actual ux library repo it uses an npm build script though.

**Comment by EisenbergEffect** [comment]
`au build` should work. I would use `au run` if you want to see the app. You would need to npm install all the libraries first and run that from within the repo, making sure you have the cli installed.

**Comment by adriatic** [comment]
My sincere apologies as I managed to confuse `https://github.com/aurelia/app-ux-showcase` with `https://github.com/aurelia/ux` so I used the wrong README. Obviously retirement time where I just sit and look through the window is approaching rapidly.

**Comment by adriatic** [comment]
Whatever little I could see in

![image](https://cloud.githubusercontent.com/assets/2712405/20025806/95a19742-a2c8-11e6-8b6a-f7d26f7e7e0a.png)

shows a lot of style!

**Comment by EisenbergEffect** [comment]
There's not much there but we've got a good foundation we can work with the community on to build.
