### ISSUE TITLE
Microsoft platform and web browsers

### ISSUE THREAD

**Issue by bsrdjan** [aurelia/ux#71]
Reading https://github.com/aurelia/ux/wiki, I found no statement about supporting Microsoft platform and web browsers. Is it out of scope or what is the plan?

**Comment by EisenbergEffect** [comment]
Microsoft browsers are supported. However, we don't currently have a plan to support Microsoft's design language. That doesn't mean we won't do it. It's just that we're doing iOS and Material design first.
