### ISSUE TITLE
Ux components from the community

### ISSUE THREAD

**Issue by inhuman-programmer** [aurelia/ux#8]
Making ux components is going to take a long time. do you need any help from the community? If yes, I am willing to help to make Aurelia great. I absolutely love material design and I'm sure the community, including me will be capable of making rich ux components that will just need to be tested before put to production. With such a great foundation i think it's a great idea. Please let us know if we should do something like that.

**Comment by bigopon** [comment]
I think the call is already there: 
[Introducing aurelia-ux](http://blog.aurelia.io/2016/11/04/introducing-aurelia-ux/)

**Comment by EisenbergEffect** [comment]
We would love the community involved. That goes for all of Aurelia, but especially the new library. If there's a component you are interested in working on, create an issue for that and then lets start specing out the design there.
