### ISSUE TITLE
Use Aurelia-UX(theme) within skeleton-esnext-webpack got a error

### ISSUE THREAD

**Issue by XuJinNet** [aurelia/ux#81]
Hello friends, i using the newest skeleton-esnext-webpack and  aurelia-ux, but got a error when build:
```
ERROR in ./src/app.html
Module not found: Error: Can't resolve 'common/styles/common-ux.css#ux' in '/Users/xujin/My_Projects/NodeJS/skeleton-esnext-webpack/src'
 @ ./src/app.html
 @ ./src/app.js
 @ ./src/main.js
 @ ./~/aurelia-webpack-plugin/dist/aurelia-entry.js
 @ multi aurelia-webpack-plugin/dist/aurelia-entry aurelia-polyfills aurelia-loader-webpack (webpack)-dev-server/client?http://localhost:8080 aurelia-bootstrapper
```
I try to rename `common-ux.css` to `common-ux.css#ux`, but got another error:
```
ERROR in ./src/common/styles/common-ux.css#ux
Module build failed: Unknown word (16:23)

  14 | }
  15 | styles.primary {
> 16 |   background-color: ${$design.primary};
     |                       ^
  17 | }
  18 | styles.left_font_color {
  19 |   color: ${$design.left_font_color};

 @ ./src/app.html
 @ ./src/app.js
 @ ./src/main.js
 @ ./~/aurelia-webpack-plugin/dist/aurelia-entry.js
 @ multi aurelia-webpack-plugin/dist/aurelia-entry aurelia-polyfills aurelia-loader-webpack (webpack)-dev-server/client?http://localhost:8080 aurelia-bootstrapper
``` 

main.js fragment
```javascript
import 'babel-polyfill';
import * as Bluebird from 'bluebird';
import i18nextBackend from 'i18next-xhr-backend';
import moment from 'moment';
import {AppRouter} from 'aurelia-router';

Bluebird.config({ warnings: { wForgottenReturn: false } });

export async function configure(aurelia) {
    aurelia.use
        .standardConfiguration()
        .developmentLogging()
        .plugin(PLATFORM.moduleName('aurelia-animator-css'))
        .plugin(PLATFORM.moduleName('aurelia-ux'))
        .feature(PLATFORM.moduleName('common'));
        ......
```

Node: 6.11.0
aurelia-ux: 0.2.0
skeleton-esnext-webpack: the master branch

**Comment by kennyfowler** [comment]
i guess this is already known, it currently just doesn't work, webpack gathers all .css files, but the dynamic css is not valid css...  so it fails on compiling them, and the whole build fails.

see https://github.com/aurelia/ux/issues/50

**Comment by EisenbergEffect** [comment]
You need webpack to treat it as text I imagine. I'm not a webpack guru though.

**Comment by mrazvan92** [comment]
Have you found a solution? :(

**Comment by mrazvan92** [comment]
Hello,

I found a solution :)

in **webpack.config.js**

1. add **ModuleDependenciesPlugin** dependencies

`const { AureliaPlugin } = require('aurelia-webpack-plugin');`

replace with 

`const { AureliaPlugin, ModuleDependenciesPlugin } = require('aurelia-webpack-plugin');`

2. replace these rules

`{
        test: /\.css$/i,
        issuer: [{ not: [{ test: /\.html$/i }] }],
        use: extractCss ? ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: cssRules,
        }) : ['style-loader', ...cssRules]
      },
      {
        test: /\.css$/i,
        issuer: [{ test: /\.html$/i }],
        // CSS required in templates cannot be extracted safely
        // because Aurelia would try to require it again in runtime
        use: cssRules
      },`

with

`{
        test: /\.css$/i,
        issuer: [{ not: [{ test: /\.html$/i }] }],
        use: extractCss ? ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: cssRules,
        }) : ['style-loader', ...cssRules],
        exclude: /aurelia-ux/
      },
      {
        test: /\.css$/i,
        issuer: [{ test: /\.html$/i }],
        // CSS required in templates cannot be extracted safely
        // because Aurelia would try to require it again in runtime
        use: cssRules,
        exclude: /aurelia-ux/
      },`

3. add these rules

`{
        test: /\.css$/i,
          loader: 'raw-loader',
        include: /aurelia-ux/,
      },`

4. add in **ModuleDependenciesPlugin** aurelia-ux dependencies

`
....
plugins: [
    new AureliaPlugin({
      includeSubModules: [{ moduleId: "aurelia-ux" }]
    }),
    new ModuleDependenciesPlugin({
      'aurelia-ux': [
        'aurelia-ux/button/ux-button-theme.css',
        'aurelia-ux/input/ux-input-theme.css',
        'aurelia-ux/form/ux-form-theme.css',
        'aurelia-ux/form/ux-field-theme.css',
        'aurelia-ux/button/ux-button-theme.css',
        'aurelia-ux/checkbox/ux-checkbox-theme.css',
        'aurelia-ux/chip-input/ux-chip-theme.css',
        'aurelia-ux/chip-input/ux-chip-input-theme.css',
        'aurelia-ux/chip-input/ux-tag-theme.css',
        'aurelia-ux/icons/ux-icon-theme.css',
        'aurelia-ux/input-info/ux-input-info-theme.css',
        'aurelia-ux/textarea/ux-textarea-theme.css'
      ]
    }),
    new ProvidePlugin({
....
`

6. and magic :D **works**

**Comment by kennyfowler** [comment]
@mrazvan92 works for me on latest webpack-typescript skeleton, just had to npm install raw-loader (used in the solution). thx!

...if someone else tries this out now: i had this related issue https://github.com/aurelia/validation/issues/445#issuecomment-305650958

...deleting contents of the aurelia-ux/node_modules folder solved it

**Comment by jemhuntr** [comment]
@mrazvan92 Thanks! This works for me too on a webpack-based Aurelia CLI project. :)

**Comment by mrazvan92** [comment]
@jemhuntr or you can check https://t.co/ajjHO9N1EL
