### ISSUE TITLE
[question] material-components-web

### ISSUE THREAD

**Issue by RobJacobs** [aurelia/ux#85]
Curious to know if consideration was given to using the material-components-web project:

https://github.com/material-components/material-components-web

They give examples for integration with Aurelia:

https://github.com/material-components/material-components-web/tree/master/framework-examples

I like the idea of using similar markup/classes regardless of the framework (like what TWBS offers).  I see Angular Material spend a lot of time on html/css issues and interpreting the Material Design guidelines that the material-components-web project is also solving, rather than just focusing on implementing a UI framework.

**Comment by EisenbergEffect** [comment]
The goal with Aurelia UX is to not only handle Material, but also iOS and Windows styles eventually. We're building it to take full advantage of Aurelia's templating and binding system, so we want to do it from scratch. If you like Material Components, there's no reason you can't use them in your Aurelia app though.
