### ISSUE TITLE
feat(icons): support for different icon providers

### ISSUE THREAD

**Issue by jemhuntr** [aurelia/ux#86]
Hey everyone! Good work on UX so far!

It would be a nice addition if we can support multiple icon providers.

Some icon providers on the wild:

- [Material Icons](https://github.com/google/material-design-icons)
- [FontAwesome Icons](http://fontawesome.io/icons/)
- [Apple Human Interface System Icons](https://developer.apple.com/ios/human-interface-guidelines/graphics/system-icons/)
- [Entypo](http://www.entypo.com/)
- [Open Iconic](https://useiconic.com/open/)

It follows that icon configuration should adapt to the design language in place.

**Comment by ZHollingshead** [comment]
Material Icons is currently supported and is the default set. We are planning to add IOS Icons in the future with the intention of changing based on the design language.
