### ISSUE TITLE
Feature list

### ISSUE THREAD

**Issue by inhuman-programmer** [aurelia/ux#9]
A list of features such as a table of features [here](https://github.com/angular/material2/blob/master/README.md) would be useful for the community so we can contribute in making UX components.

 I personally will start creating ux components at the start of December, as right now I have something else to do, but others and I would probably love such a table table, allowing us to make this ux quicker than angular material 2, simply because of our strong community.

**Comment by EisenbergEffect** [comment]
We're planning to start putting this together soon :) Thanks for the feedback.

**Comment by EisenbergEffect** [comment]
Here's the start: https://github.com/aurelia/ux/wiki/Feature-List
We'll expand this list over time of course.
