### ISSUE TITLE
<ux-input> placeholder isn't working with aurelia-i18n

### ISSUE THREAD

**Issue by khuongduybui** [aurelia/ux#96]
I tried both `<ux-input t="[placeholder]foo">` and `<ux-input placeholder.bind="foo & b">`.
The inner <input> element's placeholder attribute is empty in both cases.

**Comment by khuongduybui** [comment]
Perhaps passing the `t` attribute through to the child element will trigger aurelia-i18n on both the parent and the child and solve the problem.

**Comment by ZHollingshead** [comment]
Issue moved to [aurelia/ux-components #1](https://github.com/aurelia/ux-components/issues/1) via [**ZenHub**](https://www.zenhub.com/)
